# Python CircleCI 2.0 configuration file

version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install multiprocess
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install pytest
            pytest
      - store_artifacts:
          path: test-reports
          destination: test-reports
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7
